### ISSUE TITLE
System.IO.DirectoryNotFoundException - Nexus - Mod Manager Download

### ISSUE THREAD

**Issue by jdadian** [thomasgraham18/Fallout76-QuickConfiguration#1]
*************** Error message ***************
System.AggregateException: One or more errors occurred.

**************** System Info ****************
Operating system:  Windows 11 64-bit
Program version:   1.12.6
User agent:        Fo76QuickConfiguration/1.12.6 (Windows NT 10.0.22631.0; x64) .NETFramework/4.7.2
Running as admin:  No
System culture:    English (United States)
App locale:        en-US
Game edition:      Steam

**************** Stack Trace ****************
If any files are listed (like "at ... in ...\*.cs:line 123"):
Those are files on *my* computer, so don't worry if you can't find them.

System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Fo76ini.Mods.ModInstallations.DownloadFile(String url, String path, Action`1 ProgressChanged) in X:\Repos\Fo76\Fo76ini\Mods\ModInstallations.cs:line 263
   at Fo76ini.Mods.ModInstallations.InstallRemote(ManagedMods mods, String nxmLinkStr, Boolean useSourceBA2Archive, Action`1 ProgressChanged) in X:\Repos\Fo76\Fo76ini\Mods\ModInstallations.cs:line 220
   at Fo76ini.FormMods.<>c__DisplayClass93_0.<RunThreaded>b__0() in X:\Repos\Fo76\Fo76ini\Forms\FormMods\FormMods.cs:line 1207
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

************** Inner Exception **************
System.Net.WebException: An exception occurred during a WebClient request.

************** Inner Exception **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\Games\Steam\steamapps\common\Fallout76\Quick Configuration\Downloads\Nuka Label Fix (BA2)-1260-1-0-1639442043.7z'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)

-------------------------------------------------

After enabling "Associate with 'Mod Manager Download' links", and clicking the related download button on the nexus, QC app freezes on the downloading screen and throws the error shown above.

**Comment by thomasgraham18** [comment]
Unable to reproduce with given steps.

Please try shortening the path to the utility, ie:

'F:\Games\Steam\steamapps\common\Fallout76\QC' 

instead of 

'F:\Games\Steam\steamapps\common\Fallout76\Quick Configuration'.

You can also try running as admin, or please verify you selected the correct path when launching the program for the first time.

Example:

![image](https://github.com/thomasgraham18/Fallout76-QuickConfiguration/assets/90620889/b5d190d0-1541-4e72-a45c-180cedea44e5)

**Comment by jdadian** [comment]
Thank you, shortening the path solved my issue!
